### ISSUE TITLE
This is the worst development tool I have ever used

### ISSUE THREAD

**Issue by Xenos156156** [PyQt5/QtDesigner#1]
This is the worst development tool I have ever used. 
The controls are as hard to use as shit, and I want to punch the developer in the head.

**Comment by Mr-Second** [comment]
已收到(自动回复，不要回答！不要回答！不要回答！)

**Comment by 892768447** [comment]
> This is the worst development tool I have ever used. The controls are as hard to use as shit, and I want to punch the developer in the head.

this is only the mirror download address.

the developer in here. https://doc.qt.io/qt-5/qtdesigner-manual.html

if you can punch, you up, no can, no bb. not welcome here.
