### ISSUE TITLE
How to use it?（怎么使用它？）

### ISSUE THREAD

**Issue by children1987** [PyQt5/QtDesigner#3]
Is there a document?（是否有文档？）

**Comment by 892768447** [comment]
文档下个版本增加新功能后一起补充
目前只需要下载后解压运行designer.exe即可
Python编写界面插件参考  https://github.com/PyQt5/QtDesigner/tree/master/designer 里面的demo
同时该目录也是自定义控件的插件目录

**Comment by children1987** [comment]
好的 多谢
